In [74]:
import numpy as np

a = np.array([[1, 2, 3],[4,5,6]],dtype=np.float32)
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
2
6


In [75]:
a = np.ones((3,3))
print(a)
print("*"*50)
b = np.zeros((3,3))
print(b)
print("*"*50)
c = np.eye(3)
print(c)
print("*"*50)
d = np.diag(np.array([1,2,3,4]))
print(d)
print("*"*50)
g = np.random.rand(4,4)
print(g)
print("*"*50)
h = np.random.randn(4,4)
print(h)
print("*"*50)
z = np.arange(0,10,2)
print(z)
print("*"*50)
r = np.linspace(0,10,5)
print(r)
print("*"*50)

#create lin space matrix
x = np.linspace(0,10,25)
print(x)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
**************************************************
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
**************************************************
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
**************************************************
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
**************************************************
[[0.6217805  0.40609726 0.11752134 0.43407846]
 [0.68664659 0.67976903 0.0903893  0.64191519]
 [0.47781045 0.11271124 0.52812462 0.26234944]
 [0.90329808 0.50392779 0.57704351 0.26131168]]
**************************************************
[[-0.58507287  0.1260805  -1.03856707  0.46164199]
 [-0.7473739   1.03935235  0.59323789 -1.10112992]
 [-0.21602722  0.34543936 -0.14633966 -1.9552391 ]
 [ 1.6203091  -0.59346845  0.17233831 -0.01091928]]
**************************************************
[0 2 4 6 8]
**************************************************
[ 0.   2.5  5.   7.5 10. ]
**************************************************
[ 0

In [76]:
x.reshape(5,5)

array([[ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667],
       [ 2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ],
       [ 4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333],
       [ 6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667],
       [ 8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ]])

In [77]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(np.concatenate((a,b),axis=1))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [78]:
print(a.dtype)
print(a.astype(np.float16))

int64
[[1. 2. 3.]
 [4. 5. 6.]]


In [79]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [80]:
A = np.array([[1,2],[3,4]])
print(A)
print(A.reshape(1,4))
print(A.reshape(4,1))
print(A.reshape(4,-1))
# print(A.reshape(3,-1))  #error

[[1 2]
 [3 4]]
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [4]]


In [81]:
B = np.array([[5,6],[7,8],[9,10]])
print(B.reshape(2,-1))
print(B.reshape(1,-1))
print(B.reshape(-1,2))

[[ 5  6  7]
 [ 8  9 10]]
[[ 5  6  7  8  9 10]]
[[ 5  6]
 [ 7  8]
 [ 9 10]]


In [82]:
print(B.reshape(1,2,3))
print(B.reshape(2,1,3))
print(B.reshape(2,1,3).shape)

[[[ 5  6  7]
  [ 8  9 10]]]
[[[ 5  6  7]]

 [[ 8  9 10]]]
(2, 1, 3)


In [83]:
A = np.array([[1,2],[3,4]])
print(A)
print(A.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [84]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [85]:
# Arithmetic operations
print(mat + mat)
print("*"*50)
print(mat - mat)
print("*"*50)
print(mat * mat)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
**************************************************
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
**************************************************
[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]
 [441 484 529 576 625]]


In [86]:
# Scaler operations
print(mat + 100)
print("*"*50)
print(mat - 100)
print("*"*50)
print(mat * 100)

[[101 102 103 104 105]
 [106 107 108 109 110]
 [111 112 113 114 115]
 [116 117 118 119 120]
 [121 122 123 124 125]]
**************************************************
[[-99 -98 -97 -96 -95]
 [-94 -93 -92 -91 -90]
 [-89 -88 -87 -86 -85]
 [-84 -83 -82 -81 -80]
 [-79 -78 -77 -76 -75]]
**************************************************
[[ 100  200  300  400  500]
 [ 600  700  800  900 1000]
 [1100 1200 1300 1400 1500]
 [1600 1700 1800 1900 2000]
 [2100 2200 2300 2400 2500]]


In [87]:
# Matrix multiplication
ran_mat = np.random.randint(1,100,5).reshape(5,1)
print(ran_mat)
print(mat.dot(ran_mat))

[[38]
 [ 5]
 [97]
 [55]
 [48]]
[[ 799]
 [2014]
 [3229]
 [4444]
 [5659]]


In [88]:
# logical operations
print(mat > 10)

[[False False False False False]
 [False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [89]:
mat[mat > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [90]:
tmp = np.arange(26,51).reshape(5,5)
mat = mat.astype(np.float32)
print(tmp)
print("*"*50)
# mat += tmp
# print(mat)
# print("*"*50)
mat /= tmp
print(mat)

[[26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
**************************************************
[[0.03846154 0.07407407 0.10714286 0.13793103 0.16666667]
 [0.19354838 0.21875    0.24242425 0.2647059  0.2857143 ]
 [0.30555555 0.3243243  0.34210527 0.35897437 0.375     ]
 [0.3902439  0.4047619  0.41860464 0.4318182  0.44444445]
 [0.45652175 0.4680851  0.47916666 0.48979592 0.5       ]]


In [93]:
print(np.sqrt(mat))
print("*"*50)
print(np.exp(mat))
print("*"*50)
print(np.sin(mat))


[[0.19611613 0.27216554 0.32732683 0.37139067 0.4082483 ]
 [0.43994135 0.4677072  0.492366   0.5144958  0.5345225 ]
 [0.5527708  0.5694948  0.58489764 0.5991447  0.61237246]
 [0.62469506 0.636209   0.6469966  0.65712875 0.6666667 ]
 [0.67566395 0.68416744 0.69221866 0.6998542  0.70710677]]
**************************************************
[[1.0392108 1.0768865 1.1130934 1.1478964 1.1813605]
 [1.2135481 1.2445202 1.2743347 1.3030477 1.3307122]
 [1.357379  1.3830957 1.4079086 1.4318601 1.4549913]
 [1.4773409 1.4989455 1.5198393 1.5400549 1.5596235]
 [1.5785738 1.5969334 1.6147282 1.631983  1.6487212]]
**************************************************
[[0.03845206 0.07400636 0.10693798 0.13749409 0.16589613]
 [0.19234222 0.21700957 0.2400567  0.2616254  0.28184286]
 [0.30082303 0.3186684  0.3354711  0.35131416 0.36627254]
 [0.38041398 0.39379993 0.40648597 0.41852278 0.42995638]
 [0.44082874 0.4511782  0.46103984 0.4704458  0.47942555]]


In [ ]:
 # Indexing and slicing